trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: "Set up Python"

- script: |
    python -m pip install --upgrade pip
    pip install -r project/requirements.txt
  displayName: "Install dependencies"

- script: |
    python -c "print('Hello from Music Playlist Batch Creator!')"
  displayName: "Run test script"